responding to comments

diff --git a/cromshell b/cromshell
--- a/cromshell
+++ b/cromshell
@@ -284,39 +284,31 @@ function checkPrerequisites
 
 function assertRequiredFileIsNonEmpty()
 {
-
   local fileName=$1
   local fileDescription=$2
-  if [[ -z ${fileName} ]]
-	then
-		error "Error: required file ${fileDescription} was not specified."
-		exit 6
-	else
-		if [[ -f ${fileName} ]]
-		then
-			if [[ -s ${fileName} ]]
-			then
-				return 0
-			else
-				error "Error: file ${fileName} is an empty file."
-				exit 6
-			fi
-		else
-			error "Error: file ${fileName} does not exist."
-			exit 6;
-		fi
-	fi
+  if [[ -z ${fileName} ]]; then
+    error "ERROR: ${fileDescription} must be specified."
+  exit 6
+  else
+    if [[ -f ${fileName} ]]; then
+      if [[ ! -s ${fileName} ]]; then
+        error "ERROR: ${fileDescription} is empty: ${fileName}"
+        exit 6
+      fi
+    else
+      error "ERROR: ${fileDescription} does not exist: ${fileName}"
+      exit 6;
+    fi
+  fi
 }
 
 function assertOptionalFileIsNonEmpty()
 {
-	local fileName=$1
-	if [[ -z ${fileName} ]]
-	then
-		return 0
-	else
-		assertRequiredFileIsNonEmpty ${fileName}
-	fi
+  local fileName=$1
+  local fileDescription=$2
+  if [[ ! -z ${fileName} ]] ; then
+    assertRequiredFileIsNonEmpty "${fileName}" "${fileDescription}"
+  fi
 }
 
 function checkForComplexHelpArgument()
@@ -654,19 +646,26 @@ function submit()
   done
   shift $((OPTIND-1)) 
  
-  # ---------------------------------------- 
+  # ----------------------------------------
 
-  assertCanCommunicateWithServer $CROMWELL_URL
+  if [[ $# -lt 2 ]] ; then
+    error "ERROR: submit requires at least a WDL and JSON file."
+    error ""
+    simpleUsage submit
+    exit 21
+  fi
 
   local wdl=${1}
   local json=${2}
   local optionsJson=${3}
   local dependenciesZip=${4}
 
-  assertRequiredFileIsNonEmpty "$wdl" "wdl"
-  assertRequiredFileIsNonEmpty "$json" "input json"
-  assertOptionalFileIsNonEmpty "$optionsJson"
-  assertOptionalFileIsNonEmpty "$dependenciesZip"
+  assertRequiredFileIsNonEmpty "${wdl}" "WDL"
+  assertRequiredFileIsNonEmpty "${json}" "Input JSON"
+  assertOptionalFileIsNonEmpty "${optionsJson}" "Options JSON"
+  assertOptionalFileIsNonEmpty "${dependenciesZip}" "Dependencies Zip"
+
+  assertCanCommunicateWithServer $CROMWELL_URL
 
   local response=$(curl --connect-timeout $CURL_CONNECT_TIMEOUT --max-time $CURL_MAX_TIMEOUT -s -F workflowSource=@${wdl}  ${2:+ -F workflowInputs=@${json}} ${3:+ -F workflowOptions=@${optionsJson}} ${4:+ -F workflowDependencies=@${depdenciesZip}} ${CROMWELL_URL}/api/workflows/v1)
   local r=$?
