Adding in functionality for aliasing jobs. (#104)
- Added in functionality for aliasing jobs.
- Added in a new logo for tasks with the status DOOMED.
- Fixes #89

diff --git a/cromshell b/cromshell
--- a/cromshell
+++ b/cromshell
@@ -8,7 +8,7 @@ SCRIPTDIR="$( cd "$( dirname "${UNALIASED_SCRIPT_NAME}" )" && pwd )"
 SCRIPTNAME=$( echo $0 | sed 's#.*/##g' )
 MINARGS=1
 MAXARGS=99
-PREREQUISITES="curl jq mail column tput rev"
+PREREQUISITES="curl jq mail column tput rev base64 gunzip"
 
 # Determine if this shell is interactive:
 ISINTERACTIVESHELL=true
@@ -34,11 +34,26 @@ TASK_COLOR_FAILED='\033[0;31m'
 
 ################################################################################
 
+DOOMED_LOGO_b64gz="H4sIAOfW3l0AA6WUwXHEIAxF767i35yDQQUkTiWeYcvIgUPa2GbSwHaRSiIJAcL2zmTHeGKYj/QQ39qs625Axv+0vqyrabOB6J+mAkQv79TVIBNpGNGUs24kGbrKGV47Gz2uH1aArE5F5TcM1CKJtWURN8q7Tsi1wH54e5Roe0CDd01yf79/ZFoC8YrES10UvMuRlM4+FpuChoVkmt5s/WDW5+4Vln1KzMOn29cdZpgT2G5BRcKbK56nLEW7Pyt/SNVTklbtrpCqO2ih8O58ER73ObzzMz/uQDXGhZfyubZEudaf+GjZjJkGsoTmJ90xhmaUNiSoRVqubgsaA1SNSYc7HAIdUg2pzO1mgSO07/TyTyIHKhq0jsg9NXMiT3EU45kIEsn8J5wwo0SV/SQNZ5SSDf6gSQt1IncamfaMa1CYZ+KnJjixaFX1Gp2Xu2P2L5X0V+tlUSOlUeIOispu0FPiC0OZUIuZdxFWmeXi6u5k/1MvIkup6jZN3CXzZVplMitOf/Lm5/B8BgAA"
+
+################################################################################
+
 # Setup Cromshell config details:
 CROMSHELL_CONFIG_DIR=${HOME}/.cromshell
 mkdir -p ${CROMSHELL_CONFIG_DIR}
 CROMWELL_SUBMISSIONS_FILE="${CROMSHELL_CONFIG_DIR}/all.workflow.database.tsv"
-[[ ! -f ${CROMWELL_SUBMISSIONS_FILE} ]] && echo -e "DATE\tCROMWELL_SERVER\tRUN_ID\tWDL_NAME\tSTATUS" > ${CROMWELL_SUBMISSIONS_FILE}
+[[ ! -f ${CROMWELL_SUBMISSIONS_FILE} ]] && echo -e "DATE\tCROMWELL_SERVER\tRUN_ID\tWDL_NAME\tSTATUS\tALIAS" > ${CROMWELL_SUBMISSIONS_FILE}
+
+# Update cromshell submissions file if it needs updating:
+grep -q 'ALIAS$' ${CROMWELL_SUBMISSIONS_FILE} 
+r=$?
+if [[ $r -ne 0 ]] ; then
+  echo "Upgrading cromshell config file..." 1>&2
+  cp ${CROMWELL_SUBMISSIONS_FILE} ${CROMSHELL_CONFIG_DIR}/tmp.tmptmp
+  echo -e "DATE\tCROMWELL_SERVER\tRUN_ID\tWDL_NAME\tSTATUS\tALIAS" > ${CROMWELL_SUBMISSIONS_FILE}
+  tail -n+2 ${CROMSHELL_CONFIG_DIR}/tmp.tmptmp >> ${CROMWELL_SUBMISSIONS_FILE}
+  rm ${CROMSHELL_CONFIG_DIR}/tmp.tmptmp
+fi
 
 # Find the CROMWELL Server:
 CROMWELL_SERVER_FILE=${CROMSHELL_CONFIG_DIR}/cromwell_server.config
@@ -71,6 +86,20 @@ OPTIONS=''
 TERMINAL_STATES="Succeeded Failed Aborted"
 
 ################################################################################
+
+function doomedLogo() 
+{
+  # Figure out which decoder to use:
+  base64 -D <<<"MQo=" &> /dev/null
+  r=$?
+  if [[ $r -eq 0 ]] ; then
+    base64 -D <<<"${DOOMED_LOGO_b64gz}" | gunzip
+  else
+    base64 -d <<<"${DOOMED_LOGO_b64gz}" | gunzip
+  fi | while read line ; do 
+    error "${COLOR_FAILED}${line}${COLOR_NORM}"
+  done
+}
 
 function turtle() 
 {
@@ -134,6 +163,12 @@ function usage()
   echo -e "        included_wdl_zip_file  Zip file containing any WDL files included in the input WDL"
   echo -e ""
   echo -e "   abort [workflow-id] [[workflow-id]...]                            Abort a running workflow."
+  echo -e
+  echo -e "  Workflow information:"
+  echo -e
+  echo -e "   alias workflow-id alias                                           Label the given workflow ID with the given alias."
+  echo -e "                                                                     Aliases can be used in place of workflow IDs to reference"
+  echo -e "                                                                     jobs."
   echo -e
   echo -e "  Query workflow status:"
   echo -e "   status [workflow-id] [[workflow-id]...]                           Check the status of a workflow."
@@ -427,6 +462,42 @@ function populateLastWorkflowId()
   WORKFLOW_ID=$( tail -n1 ${CROMWELL_SUBMISSIONS_FILE} | awk '{print $3}' )
 }
 
+function alias_workflow() 
+{
+  local alias_name=${2}
+
+  # Check that we have an alias and workflow defined:
+  if [[ ${#alias_name} -eq 0 ]] || [[ ${#1} -eq 0 ]] ; then
+    error "ERROR: Cannot process alias name."
+    error "       Please specify both a workflow ID and an alias."
+    return 1
+  fi
+
+  # Check if the alias already exists:
+  awk '{print $6}' ${CROMWELL_SUBMISSIONS_FILE} | grep -v '^[ \t]*$' | grep -q "^${alias_name}$"
+  local r=$?
+  if [[ $r -eq 0 ]] ; then
+    error "ERROR: Alias already exists: ${alias_name}"
+    error "       Please choose another alias."
+    return 1
+  fi
+
+  # Get the workflow ID:
+  populateWorkflowIdAndServerUrl ${1}
+
+  error "Aliasing ${WORKFLOW_ID} -> ${alias_name}"
+  cp ${CROMWELL_SUBMISSIONS_FILE} ${CROMWELL_SUBMISSIONS_FILE}.bak
+  awk "BEGIN { FS=OFS=\"\t\" } { if (\$3 == \"${WORKFLOW_ID}\") { \$6=\"${alias_name}\"; print} else {print;} }" ${CROMWELL_SUBMISSIONS_FILE}.bak > ${CROMWELL_SUBMISSIONS_FILE} 
+  local r=$? 
+  if [[ $r -eq 0 ]] ; then
+    error "Done."
+  else 
+    error "Unable to create alias: ${WORKFLOW_ID} -> ${alias_name}"
+  fi
+
+  return $r
+}
+
 function populateWorkflowIdAndServerUrl()
 {
   local userSpecifiedId=${1}
@@ -437,10 +508,7 @@ function populateWorkflowIdAndServerUrl()
     assertHavePreviouslySubmittedAJob
     WORKFLOW_ID=$(tail -n ${row} ${CROMWELL_SUBMISSIONS_FILE} | head -n 1 | awk '{print $3}' )
     WORKFLOW_SERVER_URL=$(tail -n ${row} ${CROMWELL_SUBMISSIONS_FILE} | head -n 1 | awk '{print $2}' )
-  else
-    # If the user specified anything at this point, assume that it 
-    # is a workflow UUID:
-    if [[ -n "$userSpecifiedId" ]]; then
+  elif [[ $(matchWorkflowId ${userSpecifiedId}) -eq 0 ]] ; then
       WORKFLOW_ID=${userSpecifiedId}
       WORKFLOW_SERVER_URL=${CROMWELL_URL}
 
@@ -449,9 +517,14 @@ function populateWorkflowIdAndServerUrl()
       grep ${WORKFLOW_ID} ${CROMWELL_SUBMISSIONS_FILE} > ${tmpFile}
       r=$?
       [[ ${r} -eq 0 ]] && WORKFLOW_SERVER_URL=$( awk '{print $2}' ${tmpFile} )
-
-      # If the user specified nothing, get the last workflow ID:  
+ else
+    if [[ -n "$userSpecifiedId" ]]; then
+      # The user specified something, but it's not a relative ID or a proper id.
+      # It must be an alias.
+      WORKFLOW_ID=$(grep "\\t${userSpecifiedId}\$" ${CROMWELL_SUBMISSIONS_FILE} | head -n1 | awk '{print $3}')
+      WORKFLOW_SERVER_URL=$(grep "\\t${userSpecifiedId}\$" ${CROMWELL_SUBMISSIONS_FILE} | head -n1 | awk '{print $2}')
     else
+      # If the user specified nothing, get the last workflow ID:  
       populateLastWorkflowId
       WORKFLOW_SERVER_URL=$(tail -n1 ${CROMWELL_SUBMISSIONS_FILE} | awk '{print $2}' )
     fi
@@ -777,7 +850,7 @@ function status()
       # We could not find 'Fail' in our metadata, so our original status is correct. 
       turtle
     else
-      turtleDead
+      doomedLogo
       workflowStatus="DOOMED"
       local newTempFile=$(makeTemp)
       jq ".status=\"${workflowStatus}\" | .ID=\"${1}\"" ${tmpExecutionStatusCount} > ${newTempFile}
@@ -793,7 +866,9 @@ function status()
   checkPipeStatus "Could not read tmp file JSON data." "Could not parse JSON output from cromwell server."
 
   # Update ${CROMWELL_SUBMISSIONS_FILE}:
-  sed -i .bak -e "s#\\(.*${1}.*\\.wdl\\)\\t*.*#\\1$(printf '\t')${workflowStatus}#g" ${CROMWELL_SUBMISSIONS_FILE}
+  cp ${CROMWELL_SUBMISSIONS_FILE} ${CROMWELL_SUBMISSIONS_FILE}.bak
+  awk "BEGIN { FS=OFS=\"\t\" } { if ((\$3 == \"${1}\") && (\$2 == \"${2}\")) { \$5=\"${workflowStatus}\"; }; print }" ${CROMWELL_SUBMISSIONS_FILE}.bak > ${CROMWELL_SUBMISSIONS_FILE}
+  #sed -i .bak -e "s#\\(.*${1}.*\\.wdl\\)\\t*.*#\\1$(printf '\t')${workflowStatus}#g" ${CROMWELL_SUBMISSIONS_FILE}
 
   return ${retVal}
 }
@@ -1392,23 +1467,23 @@ function notify()
     # Let the user know we've done our job:
     echo "Spun off thread on ${hostServer} - PID = $( echo "${results}" | grep "Spun off thread on PID" | sed 's#Spun off thread on PID ##g' )"
   else
-		_rawNotify ${WORKFLOW_ID} ${email} ${WORKFLOW_SERVER_URL}
+    _rawNotify ${WORKFLOW_ID} ${email} ${WORKFLOW_SERVER_URL}
   fi
 }
 
 # Perform a raw notification without validating any input arguments.
 function _rawNotify() 
 {
-	local WORKFLOW_ID=$1
-	local email=$2
-	local WORKFLOW_SERVER_URL=$3
+  local WORKFLOW_ID=$1
+  local email=$2
+  local WORKFLOW_SERVER_URL=$3
 
-	error "Spinning off notification thread to ${email} for"
-	error "    workflow:             ${WORKFLOW_ID}" 
-	error "    from Cromwell server: ${WORKFLOW_SERVER_URL}"
-	error "..."
-	nohup bash -c "source ${SCRIPTDIR}/${SCRIPTNAME}; _notifyHelper ${WORKFLOW_ID} ${email} ${WORKFLOW_SERVER_URL}" &>/dev/null &
-	echo "Spun off thread on PID $!"
+  error "Spinning off notification thread to ${email} for"
+  error "    workflow:             ${WORKFLOW_ID}" 
+  error "    from Cromwell server: ${WORKFLOW_SERVER_URL}"
+  error "..."
+  nohup bash -c "source ${SCRIPTDIR}/${SCRIPTNAME}; _notifyHelper ${WORKFLOW_ID} ${email} ${WORKFLOW_SERVER_URL}" &>/dev/null &
+  echo "Spun off thread on PID $!"
 }
 
 # Helper function for the notify command that actually notifies the user:
@@ -1713,13 +1788,13 @@ if ${ISINTERACTIVESHELL} ; then
 
   # Validate our sub-command:
   case ${SUB_COMMAND} in
-    cleanup|submit|status|logs|execution-status-count|metadata|slim-metadata|timing|abort|notify|list|fetch-all|fetch-logs|list-outputs)
+    cleanup|submit|status|logs|execution-status-count|metadata|slim-metadata|timing|abort|notify|list|fetch-all|fetch-logs|list-outputs|alias)
       # This is a good sub-command, so we do not need to do anything. 
       ;;
-		_rawNotify)
-			# This is a valid internal sub-command.  
-			# While it should never be called directly by the user, it is possible that this was called by another command in this script.
-			;;
+    _rawNotify)
+      # This is a valid internal sub-command.  
+      # While it should never be called directly by the user, it is possible that this was called by another command in this script.
+      ;;
     *)
       if [[ ${#SUB_COMMAND} -eq 0 ]]; then
         simpleUsage 
@@ -1736,27 +1811,30 @@ if ${ISINTERACTIVESHELL} ; then
   r=$?
   [[ ${r} -ne 0 ]] && exit 6
 
-	# Sanitize the displayed sub-command:
-	SUB_COMMAND_FOR_DISPLAY=${SUB_COMMAND}
-	case ${SUB_COMMAND} in
-		_rawNotify)
-			SUB_COMMAND_FOR_DISPLAY="notify"
-			;;
-	esac
+  # Sanitize the displayed sub-command:
+  SUB_COMMAND_FOR_DISPLAY=${SUB_COMMAND}
+  case ${SUB_COMMAND} in
+    _rawNotify)
+      SUB_COMMAND_FOR_DISPLAY="notify"
+      ;;
+    alias)
+      SUB_COMMAND="alias_workflow"
+      ;;
+  esac
 
   # Handle specific sub-command args and and call our sub-command:
   error "Sub-Command: ${SUB_COMMAND_FOR_DISPLAY}"
   case ${SUB_COMMAND} in 
     # These are the sub-commands that take arguments other than workflow IDs:
-    cleanup|submit|list|notify|execution-status-count)
+    cleanup|submit|list|notify|execution-status-count|alias_workflow)
       ${SUB_COMMAND} $@
       rv=$?
       ;;
-		# These are internal sub-commands that take arguments that should not be modified:
-		_rawNotify)
-			${SUB_COMMAND} $@
-			rv=$?
-			;;
+    # These are internal sub-commands that take arguments that should not be modified:
+    _rawNotify)
+      ${SUB_COMMAND} $@
+      rv=$?
+      ;;
     # Handle sub-commands that only take workflow IDs:  
     *)
       extract_workflow_ids_from_args $@
